### ISSUE TITLE
Corda Image

### ISSUE THREAD

**Issue by RakeshChotkan** [Federated-BDI/Docker-BDI-Node#6]
I am not able to pull corda/corda-zulu-java1.8-4.5.8:latest.
Are there some registration issues?

**Comment by GearlyyDEV** [comment]
Have you been able to contact with any active support?

**Comment by Reijnn** [comment]
[Docker image](https://hub.docker.com/r/corda/corda-zulu-java1.8-4.5.8) returns a 404.

**Comment by Reijnn** [comment]
Dockerhub case: 00044278 created.
