### ISSUE TITLE
Expected an RDF value here

### ISSUE THREAD

**Issue by Reijnn** [Federated-BDI/Docker-BDI-Node#8]
When submitting the example event I get the following error message:

`Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: org.eclipse.rdf4j.rio.RDFParseException: Expected an RDF value here, found '{' [line 1]
`

I see in the email that u mentioned this error and are working on it.
Il keep the issue open until it's resolved so we can track it.

**Comment by drew3110** [comment]
Yes, we are on it, some internal mechanic of our endpoints changed.  
In the meanwhile you should be able to try with this string in the body:

```
@prefix data: <[https://ontology.tno.nl/logistics/federated/tradelens#>](https://ontology.tno.nl/logistics/federated/tradelens#%3E) .
@prefix dt: <[https://ontology.tno.nl/logistics/federated/DigitalTwin#>](https://ontology.tno.nl/logistics/federated/DigitalTwin#%3E) .
@prefix event: <[https://ontology.tno.nl/logistics/federated/Event#>](https://ontology.tno.nl/logistics/federated/Event#%3E) .
@prefix owl: <[http://www.w3.org/2002/07/owl#>](http://www.w3.org/2002/07/owl#%3E) .
@prefix pi: <[https://ontology.tno.nl/logistics/federated/PhysicalInfrastructure#>](https://ontology.tno.nl/logistics/federated/PhysicalInfrastructure#%3E) .
@prefix rdf: <[http://www.w3.org/1999/02/22-rdf-syntax-ns#>](http://www.w3.org/1999/02/22-rdf-syntax-ns#%3E) .
@prefix xsd: <[http://www.w3.org/2001/XMLSchema#>](http://www.w3.org/2001/XMLSchema#%3E) .



data:DigitalTwin-c2cb84ce-87e9-4465-bb03-79e34c4d54fe a owl:NamedIndividual, dt:Container .


data:DigitalTwin-d2cbf432-6dff-4f55-ad0a-63fccdaf5c69 a owl:NamedIndividual, dt:TransportMeans .


data:PhysicalInfrastructure-AEJEA a owl:NamedIndividual, pi:Location .


data:event-746dd77c-2b71-4b05-b928-7fcd7663e8df a owl:NamedIndividual, event:Event,
    event:LoadEvent;
  event:hasDateTimeType event:Actual;
  event:hasMilestone event:Start;
  event:hasSubmissionTimestamp "2022-09-23T12:35:01.307Z"^^xsd:dateTime;
  event:hasTimestamp "2022-10-01T11:35:01.302Z"^^xsd:dateTime;
  event:involvesBusinessTransaction data:BusinessTransaction-9c0a54d9-b152-4019-8994-283353ffdaaa;
  event:involvesDigitalTwin data:DigitalTwin-c2cb84ce-87e9-4465-bb03-79e34c4d54fe, data:DigitalTwin-d2cbf432-6dff-4f55-ad0a-63fccdaf5c69;
  event:involvesPhysicalInfrastructure data:PhysicalInfrastructure-AEJEA .
```

**Comment by Reijnn** [comment]
Above string results in the following error on my side:
`Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: org.eclipse.rdf4j.rio.RDFParseException: Unexpected character U+5B at index 0: [https://ontology.tno.nl/logistics/federated/tradelens# [line 1]
`

**Comment by drew3110** [comment]
Something went wrong in my previous copy-paste, it added square brackets. Try this:

```
@prefix data: <https://ontology.tno.nl/logistics/federated/tradelens#> .
@prefix dt: <https://ontology.tno.nl/logistics/federated/DigitalTwin#> .
@prefix event: <https://ontology.tno.nl/logistics/federated/Event#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix pi: <https://ontology.tno.nl/logistics/federated/PhysicalInfrastructure#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .



data:DigitalTwin-c2cb84ce-87e9-4465-bb03-79e34c4d54fe a owl:NamedIndividual, dt:Container .


data:DigitalTwin-d2cbf432-6dff-4f55-ad0a-63fccdaf5c69 a owl:NamedIndividual, dt:TransportMeans .


data:PhysicalInfrastructure-AEJEA a owl:NamedIndividual, pi:Location .


data:event-746dd77c-2b71-4b05-b928-7fcd7663e8df a owl:NamedIndividual, event:Event,
    event:LoadEvent;
  event:hasDateTimeType event:Actual;
  event:hasMilestone event:Start;
  event:hasSubmissionTimestamp "2022-09-23T12:35:01.307Z"^^xsd:dateTime;
  event:hasTimestamp "2022-10-01T11:35:01.302Z"^^xsd:dateTime;
  event:involvesBusinessTransaction data:BusinessTransaction-9c0a54d9-b152-4019-8994-283353ffdaaa;
  event:involvesDigitalTwin data:DigitalTwin-c2cb84ce-87e9-4465-bb03-79e34c4d54fe, data:DigitalTwin-d2cbf432-6dff-4f55-ad0a-63fccdaf5c69;
  event:involvesPhysicalInfrastructure data:PhysicalInfrastructure-AEJEA .
```

**Comment by Reijnn** [comment]
`Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
`
I dont see any services being down in the logging. I've attached them in a [pastebin](https://pastebin.com/NKFNVmMu)
password: bdi

**Comment by drew3110** [comment]
Have you checked your node is reachable from the outside?

**Comment by Reijnn** [comment]
Doesn't seem to be.
I've configured the following rule:
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/14186884/196660091-e423411d-b822-4c0d-8e10-d7823113d457.png">

**Comment by Reijnn** [comment]
I've retried posting the event on a system where it had previously worked but i'm receiving the same error: 
`Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: java.net.ConnectException: Connection refused (Connection refused)
`
Wouldn't it be more likely that it fails to connect to the local corda node?

**Comment by drew3110** [comment]
> Doesn't seem to be.

If it's not reachable from the outside that's most likely the problem.

> `Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: java.net.ConnectException: Connection refused (Connection refused)`

I experienced the same error when I tried it on a machine that I thought it was reachable from the outside (and it wasn't).

Do you have other logs besides this exception?

**Comment by RakeshChotkan** [comment]
I have received the same error when trying to post an event. The NAT is definitely correct configured.

`Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: java.net.ConnectException: Connection refused (Connection refused)`

![Schermafbeelding 2022-10-26 115920](https://user-images.githubusercontent.com/47205952/197998049-485a3256-af81-4a37-aa40-1df9bf25fa6d.png)

**Comment by MasX** [comment]
> I have received the same error when trying to post an event. The NAT is definitely correct configured.
> 
> `Something went wrong: java.util.concurrent.ExecutionException: net.corda.core.CordaRuntimeException: java.net.ConnectException: Connection refused (Connection refused)`
I see two problems:
Your node's p2p address advertises as `localhost:10005`. Other nodes won't be able to reach this. I'll remove this entry from the network map, so please re-register your node.
Additionally, your internal ip address in the screenshot refers to an ip address commonly held by the router. Are you sure 192.168.1.1 is where your node is running?

**Comment by Reijnn** [comment]
Since commit 262ae409-c583-455c-b139-3bd037420180 I can post and recieve events again.
